[package]
name = "rclin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
crossterm = "0.25.0"
trash = { version = "2.1.5", default-features = false }
tui = "0.19.0"
